name: 'f1_project'
version: '1.0'
config-version: 2

profile: 'f1_project'

vars:
  raw_dataset: 'f1_raw'

model-paths: ["models"]

models:
  f1_project:
    staging:
      materialized: view
    marts:
      core:
        materialized: table
      views:
        materialized: view