# docker/Dockerfile.ingestion
FROM python:3.9-slim

# Installer les dépendances nécessaires
RUN pip install requests google-cloud-storage google-cloud-bigquery

COPY ./sa.json /app/sa.json
# Copier les scripts d’ingestion et d’upload
COPY docker/scripts/upload_processed.py /app/upload_processed.py

# Ne PAS copier le fichier de credentials ici (on le monte depuis docker-compose)

